version: '3.7'

services:
  transmission:
    image: "linuxserver/transmission:latest"
    restart: always
    container_name: "transmission"
    volumes:
      - "./config/transmission:/config"
      - "/share/Download/.transmission/incomplete:/incomplete"
      - "/share/Download:/downloads"
    env_file:
      - .env
      - .transmission.env
    ports:
      - 9091:9091
      - 51336:51336
      - 51336:51336/udp
    logging:
      driver: json-file
      options:
        max-size: 1m
    labels:
      traefik.enable: true
      traefik.http.routers.transmission.entrypoints: websecure
      traefik.http.routers.transmission.tls: true
      traefik.http.routers.transmission.middlewares: Authelia@file, HstsHeader@file, RateLimit@file
      traefik.http.routers.transmission.service: transmission
      traefik.http.services.transmission.loadbalancer.server.port: 9091
      traefik.http.services.transmission.loadbalancer.server.scheme: http

  sonarr:
    image: "linuxserver/sonarr:latest"
    restart: always
    container_name: "sonarr"
    volumes:
      - ./config/sonarr:/config
      - /share/Download:/downloads
      - /share/Media/Videos:/tv
    ports:
      - "8989:8989"
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: 1m
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.entrypoints: websecure
      traefik.http.routers.sonarr.tls: true
      traefik.http.routers.sonarr.middlewares: Authelia@file, HstsHeader@file, RateLimit@file
      traefik.http.routers.sonarr.service: sonarr
      traefik.http.services.sonarr.loadbalancer.server.port: 8989
      traefik.http.services.sonarr.loadbalancer.server.scheme: http

  radarr:
    image: "linuxserver/radarr:latest"
    restart: always
    container_name: "radarr"
    volumes:
      - "./config/radarr:/config"
      - "/share/Download:/downloads"
      - "/share/Media/Videos:/media"
    ports:
      - "7878:7878"
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: 1m
    labels:
      traefik.enable: true
      traefik.http.routers.radarr.entrypoints: websecure
      traefik.http.routers.radarr.tls: true
      traefik.http.routers.radarr.middlewares: Authelia@file, HstsHeader@file, RateLimit@file
      traefik.http.routers.radarr.service: radarr
      traefik.http.services.radarr.loadbalancer.server.port: 7878
      traefik.http.services.radarr.loadbalancer.server.scheme: http

  metube:
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    # ports:
    #   - "8081:8081"
    env_file:
      - .env
    environment:
      YTDL_OPTIONS: "{\"cookiefile\": \"/cookies/cookies.txt\"}"
    volumes:
      - "/share/Download/metube:/downloads"
      - "./config/metube:/cookies"
    logging:
      driver: json-file
      options:
        max-size: 1m
    labels:
      traefik.enable: true
      traefik.http.routers.metube.entrypoints: websecure
      traefik.http.routers.metube.tls: true
      traefik.http.routers.metube.middlewares: Authelia@file, HstsHeader@file, RateLimit@file
      traefik.http.routers.metube.service: metube
      traefik.http.services.metube.loadbalancer.server.port: 8081
      traefik.http.services.metube.loadbalancer.server.scheme: http

  drop:
    image: lscr.io/linuxserver/pwndrop:latest
    container_name: pwndrop
    restart: unless-stopped
    env_file:
      - .env
      - .pwndrop.env
    volumes:
      - ./config/pwndrop:/config
      - /share/Download/pwndrop:/config/data/files/
    # ports:
    #   - 8080:8080
    labels:
      traefik.enable: true
      traefik.http.routers.drop.entrypoints: websecure
      traefik.http.routers.drop.tls: true
      traefik.http.routers.drop.middlewares: Authelia@file, HstsHeader@file, RateLimit@file
      traefik.http.routers.drop.service: drop
      traefik.http.services.drop.loadbalancer.server.port: 8080
      traefik.http.services.drop.loadbalancer.server.scheme: http

networks:
  default:
    external:
      name: "proxy-network"
