version: '3.7'

services:
  transmission:
    image: "linuxserver/transmission:latest"
    restart: always
    container_name: "transmission"
    volumes:
      - "./config/transmission:/config"
      - "/share/Download/.transmission/incomplete:/incomplete"
      - "/share/Download:/downloads"
    env_file:
      - .env
      - .transmission.env
    ports:
      - 9091:9091
      - 51336:51336
      - 51336:51336/udp
    labels:
      traefik.enable: true
      traefik.http.routers.transmission.entrypoints: websecure
      traefik.http.routers.transmission.tls: true
      traefik.http.routers.transmission.middlewares: Authelia@file, HstsHeader@file, RateLimit@file
      traefik.http.routers.transmission.service: transmission
      traefik.http.services.transmission.loadbalancer.server.port: 9091
      traefik.http.services.transmission.loadbalancer.server.scheme: http

  sonarr:
    image: "linuxserver/sonarr:latest"
    restart: always
    container_name: "sonarr"
    volumes:
      - ./config/sonarr:/config
      - /share/Download:/downloads
      - /share/Media/Videos:/tv
    ports:
      - "8989:8989"
    env_file:
      - .env
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.entrypoints: websecure
      traefik.http.routers.sonarr.tls: true
      traefik.http.routers.sonarr.middlewares: Authelia@file, HstsHeader@file, RateLimit@file
      traefik.http.routers.sonarr.service: sonarr
      traefik.http.services.sonarr.loadbalancer.server.port: 8989
      traefik.http.services.sonarr.loadbalancer.server.scheme: http

  radarr:
    image: "linuxserver/radarr:latest"
    restart: always
    container_name: "radarr"
    volumes:
      - "./config/radarr:/config"
      - "/share/Download:/downloads"
      - "/share/Media/Videos:/media"
    ports:
      - "7878:7878"
    env_file:
      - .env
    labels:
      traefik.enable: true
      traefik.http.routers.radarr.entrypoints: websecure
      traefik.http.routers.radarr.tls: true
      traefik.http.routers.radarr.middlewares: Authelia@file, HstsHeader@file, RateLimit@file
      traefik.http.routers.radarr.service: radarr
      traefik.http.services.radarr.loadbalancer.server.port: 7878
      traefik.http.services.radarr.loadbalancer.server.scheme: http

networks:
  default:
    external:
      name: "proxy-network"
